<h1 class="text-center">Work With Numpy </h1>

<img src="images/numpy_logo.png">

<h2>What can you do with Numpy?</h2>


NumPy can be used to perform a wide variety of mathematical operations on arrays. 

It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.


<h2>Installing NumPy</h2>


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### How to import NumPy

To access NumPy and its functions import it in your Python code like this:



In [4]:
import numpy as np

We shorten the imported name to np for better readability of code using NumPy

## difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. 

While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

**NumPy arrays are faster and more compact than Python lists**

An array consumes less memory and is convenient to use

## Simple Arrays :

In [11]:
#using Lists:
names=np.array(['ali','reza','hossein','AmirHossein'])

print(names)

#using tuples:
names=np.array(('ali','reza','hossein','AmirHossein'))
print(names)

['ali' 'reza' 'hossein' '10']
['ali' 'reza' 'hossein' 'AmirHossein']


## Dimensional Arrays

In [4]:
myArray=np.array([['ali','reza'],['hossein','AmirHossein']])

print(myArray.ndim)

2


## Access Array Elements

In [8]:
print(names[2])

hossein


### access 2d array items

In [5]:
print(myArray[1,0])

hossein


## Slicing arrays

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#from index 1 to before index 5
print(arr[1:5])


[2 3 4 5]


In [22]:
# Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [23]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


## Data Types in NumPy

In [27]:
# Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [28]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


## Converting Data Type on Existing Arrays

The **astype()** function creates a copy of the array , and allows you to specify the data type as a parameter


In [5]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i') # i for Interger , f for float and ...

#or like this : 
newarr = arr.astype(int)

print(newarr)

print(newarr.dtype)

[1 2 3]
int32


## Copy vs Views in Arrays

The main difference between a copy and a view of an array is that the **copy is a new array, and the view is just a view of the original array** .

#### Copy:

In [30]:
#The copy SHOULD NOT be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


#### View:

In [31]:
#The view SHOULD be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [32]:
#The original array SHOULD be affected by the changes made to the view.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


[31  2  3  4  5]
[31  2  3  4  5]


## NumPy Array Shape

In [35]:
#The shape of an array is the number of elements in each dimension.

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


## NumPy Array Reshaping
Reshaping means changing the shape of an array.  
The shape of an array is the number of elements in each dimension.

### Reshape From 1-D to 2-D

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## NumPy Array Iterating

Iterating means going through elements one by one.

In [39]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


### Iterating 2-D Arrays

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.



In [7]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Enumerated Iteration Using ndenumerate()

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.


In [42]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


## NumPy Joining Array
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [43]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.



In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


# NumPy Splitting Array

Splitting is reverse operation of Joining.



In [53]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,3)

# print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

#The return value is an array containing three arrays.

[1 2]
[3 4]
[5 6]


**Note**:  
We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

# NumPy Searching Arrays

To search an array, use the where() method.


In [9]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
#The example above will return a tuple: (array([3, 5, 6],)


(array([3, 5, 6], dtype=int64),)


### Search From the Right Side


In [57]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)


2


# NumPy Sorting Arrays


In [59]:
arr = np.array([3, 2, 0, 1])

#This method returns a copy of the array, leaving the original array unchanged.

print(np.sort(arr))


[0 1 2 3]


# NumPy Filter Array
In NumPy, you filter an array using a boolean index list.

**A boolean index list is a list of booleans corresponding to indexes in the array.**

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.



In [60]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


## Creating the Filter Array


In [61]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.



In [62]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]
