# NumPy ufuncs

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.



## Add the Elements of Two Lists

list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

Without ufunc, we can use Python's built-in zip() method:



In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


NumPy has a ufunc for this, called add(x, y) that will produce the same result.



In [2]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)


[ 5  7  9 11]


## Summations

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)


12


If you specify axis=1, NumPy will sum the numbers in each array.



In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


# Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The *frompyfunc()* method takes the following arguments:

**function** - the name of the function.  
**inputs** - the number of input arguments (arrays).  
**outputs** - the number of output arrays.  


In [4]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))


[6 8 10 12]


# Rounding Decimals

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.



In [5]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)


[-3.  3.]


# Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2



In [12]:
arr = np.around(3.1666, 2)

print(arr)


3.17


The floor() function rounds off decimal to nearest lower integer.



In [13]:
arr = np.floor([-3.1666, 3.6667])

print(arr)


[-4.  3.]


The ceil() function rounds off decimal to nearest upper integer.



In [15]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)


[-3.  4.]


## Product

In [19]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)


24


## Differences

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]



In [20]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)


[  5  10 -20]
