# Random Numbers in NumPy

In [22]:
from numpy import random
import numpy as np

#Generate a random integer from 0 to 100:
x=random.randint(150)

print(x)

143


In [6]:
#Generate a random float from 0 to 1:
x = random.rand()

print(x)

0.9418314798157784


## Random Array

In [12]:
x=random.randint(100, size=5)

print(x)

[18 18 50 11 37]


Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [11]:
x = random.randint(100, size=(3, 5))

print(x)


[[33 22 86 64 67]
 [64 42  2 59 20]
 [ 9 28 39 25 25]]


The rand() method also allows you to specify the shape of the array.

In [13]:
x = random.rand(5)

print(x)


[0.92501685 0.11097263 0.93329325 0.2769391  0.3846503 ]


In [15]:
x = random.rand(3, 5)

print(x)

[[0.58775951 0.72850819 0.01873278 0.84464297 0.98259167]
 [0.32558997 0.86465354 0.26309737 0.41802567 0.51774636]
 [0.30486859 0.02756544 0.8560898  0.78494847 0.39375327]]


## Generate Random Number From Array


The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.



In [17]:
x = random.choice([3, 5, 7, 9])

print(x)

5


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [18]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 3 5 7]
 [3 5 5 3 5]
 [3 3 3 3 3]]


# Random Data Distribution


Data Distribution is a list of all possible values, and how often each value occurs.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

In [20]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 7 5 7 7 5 5 7 5 7 5 7 7 7 5 7 7 5 7 7 7 7 7 7 7 7 7 7 7 5 7 5 7
 7 3 5 7 7 5 5 5 5 5 7 3 5 5 5 5 7 5 5 5 5 7 3 7 7 7 7 7 5 5 7 7 7 5 5 7 7
 7 5 7 7 7 5 5 5 7 7 3 5 7 7 5 7 5 7 7 5 3 7 3 7 5 7]


In [21]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 7 5 7]
 [5 7 7 7 5]
 [5 5 7 5 7]]


# Random Permutations

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

## Shuffling Arrays

In [28]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)


[4 5 3 1 2]


**The shuffle() method makes changes to the original array.**

## Generating Permutation of Arrays

In [29]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))


[4 3 1 2 5]


**The permutation() method returns a re-arranged array (and leaves the original array un-changed).**

# Normal (Gaussian) Distribution

Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.



In [31]:
x = random.normal(size=(2, 3))

print(x)


[[-0.44292649 -1.27796373  0.92009082]
 [ 0.28015168 -0.0599926  -0.73918261]]


Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2:
    

In [33]:
x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)


[[-2.08505354  7.18145921  0.35397424]
 [-2.39110946  0.4751597   1.47375913]]
